config/routes.rb
Rails.application.routes.draw do
  get 'static_reviews/home'
root 'static_reviews#home'
 
  resources :reviews
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  STARS = []
  PRICES = ["$$$$$", "$$$$", "$$$", "$$", "$"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(reviews_params)

    if @review.save
      redirect_to reviews_path
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])

    if @review.update(reviews_params)
      redirect_to reviews_path
    else
      render :edit
    end
  end

  def destroy
    Review.find(params[:id]).destroy
    redirect_to reviews_path
  end


private

  def reviews_params
    params.require(:review).permit(:title, :address, :rating, :food, :price, :comment)
  end
end

app/controllers/static_reviews_controller.rb
class StaticReviewsController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/static_reviews_helper.rb
module StaticReviewsHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to "Home", root_path %>
<%= link_to "Reviews", reviews_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yelp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/reviews/edit.html.erb
<h1>Edit A Review</h1>
<%= form_for @review do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :rating %>
  <%= f.number_field :rating %>

  <%= f.label :food %>
  <%= f.text_field :food %>

  <%= f.label :price %>
  <%= f.collection_select :price, Review::PRICES, :to_s, :to_s, :include_blank => true %>

  <%= f.label :comment %>
  <%= f.text_area :comment %>

  <%= f.submit %>
<% end %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>
<%= link_to 'Add Review', new_review_path %>
<% @reviews.each do |review| %>
  <h2><%= review.title %></h2>
  <%= link_to 'View', review_path(review) %>
  <%= link_to 'Edit', edit_review_path(review) %>
  <%= link_to 'Delete', review, method: :delete %>
  <% end %>

app/views/reviews/new.html.erb
<h1>Add A Review</h1>
<%= form_for @review do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :rating %>
  <%= f.number_field :rating %>

  <%= f.label :food %>
  <%= f.text_field :food %>

  <%= f.label :price %>
  <%= f.collection_select :price, Review::PRICES, :to_s, :to_s, :include_blank => true %>

  <%= f.label :comment %>
  <%= f.text_area :comment %>

  <%= f.submit %>
<% end %>

app/views/reviews/show.html.erb
<html>
<head>
 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<h1><%= @review.title %></h1>
<h4><%= @review.address %></h4>
<h2><%= @review.rating %></h4>
<h5><%= @review.food %></h5>
<h5><%= @review.price %></h5>
<h3><%= @review.comment %></h3>
<%= link_to "Back", reviews_path %>
</body>
</html>

app/views/static_reviews/home.html.erb
<h1>StaticReviews#home</h1>
<p>Find me in app/views/static_reviews/home.html.erb</p>